#!/bin/sh
#
# /etc/init.d/supervisord
#
# Supervisor is a client/server system that
# allows its users to monitor and control a
# number of processes on UNIX-like operating
# systems.
#
# chkconfig: - 64 36
# description: Supervisor Server
# processname: supervisord

# Source init functions
. /etc/init.d/functions

RETVAL=0
prog="supervisord"
pidfile="/tmp/supervisord.pid"
lockfile="/var/lock/subsys/supervisord"
SUPERVISORD="/usr/bin/supervisord"

start()
{
  echo -n $"Starting $prog: "
  daemon --pidfile $pidfile $SUPERVISORD -c /etc/supervisord.conf
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch ${lockfile}
}

stop()
{
  echo -n $"Shutting down $prog: "
  killproc -p ${pidfile} $SUPERVISORD
  RETVAL=$?
  echo
  if [ $RETVAL -eq 0 ] ; then
    rm -f ${lockfile} ${pidfile}
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status $prog
    ;;
  restart)
    stop
    start
  ;;
  *)
  echo "Usage: $0 {start|stop|restart|status}"
  ;;
esac
